version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: azapfy:php8.2-nginx
        container_name: azapfy-app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/app
        networks:
            - azapfy
    db:
        image: mysql:8.0.33
        container_name: azapfy-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_DATABASE: 'azapfy'
            MYSQL_USER: 'azapfy'
            MYSQL_PASSWORD: '123456'
        volumes:
            - ./.database:/var/lib/mysql
        ports:
            - "3307:3306"
        expose:
            - 3307
        depends_on:
            - app
        networks:
            - azapfy
    phpmyadmin:
        image: phpmyadmin
        container_name: azapfy-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_PMADB: azapfy
        ports:
            - "8001:80"
        depends_on:
            - db
        networks:
            - azapfy
    rabbit:
        image: rabbitmq:management
        container_name: azapfy-rabbitmq
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: 'azapfy'
            RABBITMQ_DEFAULT_PASS: '123456'
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - azapfy
networks:
    azapfy:
        driver: bridge

